# THIS FILE IS AUTOMATICALLY GENERATED.  EDIT THE SOURCE FILE NOT THIS ONE

"""Various descriptions of data specific to LG VX8350"""

from p_lgvx8550 import *
# same as the VX-8550 except as noted below

